apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 995673420677.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:6ef05ff4801c99716fcaf6d65b85c9c5755c88bf
        ports:
        - containerPort: 80
