apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:14406379c006ca18495339fd53fe528f0dff9901
        ports:
        - containerPort: 80
