apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 995673420677.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:6ef05ff4801c99716fcaf6d65b85c9c5755c88bf
        ports:
        - containerPort: 80
