apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:66d83d95195772032419d5e9d7a7a1bb162a05da
        ports:
        - containerPort: 80
