apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 995673420677.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:6ef05ff4801c99716fcaf6d65b85c9c5755c88bf
        ports:
        - containerPort: 80
